file:
- tfplan.json
skip-check:
- CKV_AWS_130 # Using public subnets in dev for cost.
- CKV_AWS_352 # Allow all ingress from within the VPC.
- CKV_AWS_231 # Allow ephemeral ports for egress-return traffic
- CKV_AWS_338 # Allow shorter cloudwatch log retention for cost.
- CKV_AWS_65  # Disable container insights in dev for cost.
- CKV2_AWS_11 # Disable VPC flow logs in dev for cost.
- CKV2_AWS_5  # Temp disable until tasks are ready.
quiet: true